[package]
name = "murl"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = {version ="4.5.15", features =["derive"]}
tokio = {version ="1.0", features = ["full"]}
reqwest = {version = "0.11", features = ["json"]}
